"""Initial Migration for Staging

Revision ID: 0086aaff3b32
Revises: 
Create Date: 2024-09-09 09:34:51.971495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0086aaff3b32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='deltruck'
    )
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone_1', sa.Integer(), nullable=True),
    sa.Column('telefone_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='deltruck'
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='deltruck'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='deltruck'
    )
    op.create_table('sexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='deltruck'
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linha_1', sa.String(), nullable=True),
    sa.Column('linha_2', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('id_cidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cidade'], ['deltruck.cidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deltruck'
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primeiro_nome', sa.String(), nullable=False),
    sa.Column('ultimo_nome', sa.String(), nullable=False),
    sa.Column('num_identificacao', sa.String(), nullable=True),
    sa.Column('id_sexo', sa.Integer(), nullable=True),
    sa.Column('id_contacto', sa.Integer(), nullable=True),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_contacto'], ['deltruck.contacto.id'], ),
    sa.ForeignKeyConstraint(['id_endereco'], ['deltruck.endereco.id'], ),
    sa.ForeignKeyConstraint(['id_sexo'], ['deltruck.sexo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_identificacao'),
    schema='deltruck'
    )
    op.create_table('transportadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_contacto', sa.Integer(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contacto'], ['deltruck.contacto.id'], ),
    sa.ForeignKeyConstraint(['id_endereco'], ['deltruck.endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='deltruck'
    )
    op.create_table('encomenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_encomenda', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_pessoa_cliente_final', sa.Integer(), nullable=False),
    sa.Column('id_transportadora', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa_cliente_final'], ['deltruck.pessoa.id'], ),
    sa.ForeignKeyConstraint(['id_transportadora'], ['deltruck.transportadora.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deltruck'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_modificacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('profile_img_url', sa.String(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['deltruck.pessoa.id'], ),
    sa.ForeignKeyConstraint(['id_role'], ['deltruck.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    schema='deltruck'
    )
    op.create_table('loc_encomenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('data_localizacao_encomenda', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_encomenda', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_encomenda'], ['deltruck.encomenda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='deltruck'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loc_encomenda', schema='deltruck')
    op.drop_table('user', schema='deltruck')
    op.drop_table('encomenda', schema='deltruck')
    op.drop_table('transportadora', schema='deltruck')
    op.drop_table('pessoa', schema='deltruck')
    op.drop_table('endereco', schema='deltruck')
    op.drop_table('sexo', schema='deltruck')
    op.drop_table('role', schema='deltruck')
    op.drop_table('permission', schema='deltruck')
    op.drop_table('contacto', schema='deltruck')
    op.drop_table('cidade', schema='deltruck')
    # ### end Alembic commands ###
